#!/usr/bin/env python3
"""
schema.py

Purpose
-------
Define the core data structures used throughout the Breakdance
ONT SV interpretation pipeline.

These schema objects provide the shared in-memory representation for:
- raw SV calls parsed from caller VCFs
- harmonized breakpoint junctions
- junction clusters
- interpreted events
- lightweight breakpoint graph export

Design notes
------------
This is a Version 1 schema layer intended to support:
- multi-caller ONT SV harmonization
- clustering of related rearrangement junctions
- interval-based annotation
- candidate event interpretation
- ranking / prioritization
- downstream graph export

These classes are plain dataclasses to keep the code readable,
serializable, and easy to extend.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Optional


@dataclass
class RawSVCall:
    """
    One structural variant record parsed directly from a caller VCF.

    Fields
    ------
    caller
        Caller label, e.g. sniffles2, cutesv, or svim.

    record_id
        Original VCF ID field.

    svtype
        Normalized SV type such as DEL, DUP, INV, INS, or BND.

    chrom1, pos1, chrom2, pos2
        Breakpoint coordinates.

    strand1, strand2
        Optional orientation information inferred from BND notation.

    svlen
        Parsed SV length when available.

    support
        Normalized caller-specific support estimate.

    qual
        Parsed VCF QUAL field if available.

    filt
        VCF FILTER field.

    source_path
        Path to the original VCF file.

    sample_name
        Sample identifier, usually derived from the BAM filename.

    info
        Parsed INFO dictionary from the original VCF record.

    adaptive_local_density_hint
        Density-based breakpoint enrichment hint.

    adaptive_hotspot_hint
        Boolean marker for dense breakpoint neighborhoods.
    """
    caller: str
    record_id: str
    svtype: str
    chrom1: str
    pos1: int
    chrom2: str
    pos2: int

    strand1: Optional[str] = None
    strand2: Optional[str] = None

    svlen: Optional[int] = None
    support: Optional[int] = None
    qual: Optional[float] = None
    filt: str = "PASS"

    source_path: Optional[str] = None
    sample_name: Optional[str] = None

    info: dict[str, Any] = field(default_factory=dict)

    adaptive_local_density_hint: Optional[float] = None
    adaptive_hotspot_hint: Optional[bool] = None


@dataclass
class HarmonizedJunction:
    """
    Consensus breakpoint event generated by harmonizing similar calls
    across multiple SV callers.
    """
    junction_id: str

    svtype: str
    chrom1: str
    pos1: int
    chrom2: str
    pos2: int

    strand1: Optional[str] = None
    strand2: Optional[str] = None

    callers: list[str] = field(default_factory=list)
    raw_call_ids: list[str] = field(default_factory=list)
    support_by_caller: dict[str, Optional[int]] = field(default_factory=dict)
    qual_by_caller: dict[str, Optional[float]] = field(default_factory=dict)
    filters_by_caller: dict[str, str] = field(default_factory=dict)
    source_files: list[str] = field(default_factory=list)

    caller_count: int = 0
    median_support: Optional[float] = None
    confidence: str = "low"

    chrom_pair: Optional[str] = None
    is_interchromosomal: bool = False

    adaptive_hotspot_cluster: bool = False
    adaptive_density_score: Optional[float] = None

    annotations: dict[str, Any] = field(default_factory=dict)


@dataclass
class SVCluster:
    """
    Group of harmonized junctions connected by breakpoint proximity.

    This is the main output of the clustering stage.
    """
    cluster_id: str

    junction_ids: list[str] = field(default_factory=list)
    chromosomes: list[str] = field(default_factory=list)

    junction_count: int = 0
    interchromosomal_junction_count: int = 0

    caller_set: list[str] = field(default_factory=list)

    max_adaptive_density_score: Optional[float] = None
    any_adaptive_hotspot: bool = False

    min_position_by_chrom: dict[str, int] = field(default_factory=dict)
    max_position_by_chrom: dict[str, int] = field(default_factory=dict)

    notes: dict[str, Any] = field(default_factory=dict)
    annotations: dict[str, Any] = field(default_factory=dict)


@dataclass
class InterpretedEvent:
    """
    Candidate interpreted biological / structural event.

    Examples
    --------
    - fusion_candidate
    - exon_disruption
    - promoter_hijack_candidate
    - enhancer_hijack_candidate
    - interchromosomal_rearrangement
    - complex_rearrangement_cluster
    - chromothripsis_like_cluster
    """
    event_id: str
    event_type: str
    sample: str

    junction_ids: list[str] = field(default_factory=list)
    cluster_id: Optional[str] = None

    genes: list[str] = field(default_factory=list)
    details: dict[str, Any] = field(default_factory=dict)

    confidence: str = "low"
    priority_score: float = 0.0
    priority_tier: str = "Tier3"


@dataclass
class BreakpointGraph:
    """
    Lightweight breakpoint graph export object.

    Version 1 graph model
    ---------------------
    - nodes: breakpoint endpoints
    - edges: harmonized junction links
    """
    sample: str
    nodes: list[dict[str, Any]] = field(default_factory=list)
    edges: list[dict[str, Any]] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)
