#!/usr/bin/env python3
"""
setup_references.py

Purpose
-------
Create a Breakdance-compatible reference directory for hg19, hg38, or T2T/hs1.

This script builds a standardized reference layout and installs:
- genome FASTA
- gene annotation GTF
- BED4 files for all genes
- BED4 files for all exons
- BED4 files for all promoters
- optional enhancer BED

Supported builds
----------------
- hg19
- hg38
- t2t

Directory layout
----------------
<reference_root>/
  <build>/
    genome/
      genome.fa
      genome.fa.gz
      genome.fa.fai        # if provided or already present
    annotation/
      gtf/
        genes.gtf.gz
      bed/
        genes.bed
        exons.bed
        promoters.bed
        enhancers.bed      # optional
    source_files/
    manifests/
      reference_manifest.tsv

Design notes
------------
- genes/exons/promoters are built from the full annotation GTF, not a subset
- promoters are generated as TSS-centered windows:
    default = 2000 bp upstream + 500 bp downstream
- enhancer installation is optional because there is no single universal source
- FASTA indexing is not generated by samtools here; if you want .fai creation,
  either provide an existing index or run samtools faidx afterward

Examples
--------
hg38 using defaults:
python setup_references.py --build hg38 --reference-root references

hg19 using defaults:
python setup_references.py --build hg19 --reference-root references

T2T using explicit URLs:
python setup_references.py \
  --build t2t \
  --reference-root references \
  --fasta-url https://example.org/hs1.fa.gz \
  --gtf-url https://example.org/hs1.annotation.gtf.gz

Use local files instead of downloading:
python setup_references.py \
  --build hg38 \
  --reference-root references \
  --fasta /path/to/genome.fa.gz \
  --gtf /path/to/gencode.v47.annotation.gtf.gz
"""

from __future__ import annotations

import argparse
import csv
import gzip
import os
import re
import shutil
import sys
import urllib.request
from pathlib import Path


# ---------------------------------------------------------------------
# Default sources
# ---------------------------------------------------------------------

DEFAULTS = {
    "hg38": {
        "fasta_url": "https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_47/GRCh38.primary_assembly.genome.fa.gz",
        "gtf_url": "https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_47/gencode.v47.annotation.gtf.gz",
        "build_label": "GRCh38 / hg38",
    },
    "hg19": {
        "fasta_url": "https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_47/GRCh37_mapping/GRCh37.primary_assembly.genome.fa.gz",
        "gtf_url": "https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_47/GRCh37_mapping/gencode.v47lift37.annotation.gtf.gz",
        "build_label": "GRCh37 / hg19",
    },
    "t2t": {
        # No universal default URLs imposed here because T2T sources can vary.
        "fasta_url": None,
        "gtf_url": None,
        "build_label": "T2T / hs1",
    },
}


# ---------------------------------------------------------------------
# Logging / errors
# ---------------------------------------------------------------------

def log(msg: str) -> None:
    print(msg, flush=True)


def fail(msg: str, code: int = 1) -> None:
    print(f"ERROR: {msg}", file=sys.stderr, flush=True)
    sys.exit(code)


# ---------------------------------------------------------------------
# Utility functions
# ---------------------------------------------------------------------

def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def download_file(url: str, dest: Path) -> None:
    """
    Download a file from URL to destination path.
    """
    log(f"Downloading: {url}")
    log(f"  -> {dest}")
    urllib.request.urlretrieve(url, dest)


def copy_or_symlink(src: Path, dest: Path, symlink: bool = False) -> None:
    """
    Copy or symlink a local file into the reference tree.
    """
    if not src.exists():
        fail(f"Local file does not exist: {src}")

    if dest.exists():
        dest.unlink()

    if symlink:
        dest.symlink_to(src.resolve())
    else:
        shutil.copy2(src, dest)


def open_text_auto(path: Path):
    """
    Open plain text or gzip-compressed text file.
    """
    if str(path).endswith(".gz"):
        return gzip.open(path, "rt")
    return path.open("r")


def parse_gtf_attributes(attr_str: str) -> dict[str, str]:
    """
    Parse the attributes column of a GTF line.

    Example attribute field:
      gene_id "ENSG...";
      gene_name "TP53";
      gene_type "protein_coding";
    """
    attrs = {}
    for match in re.finditer(r'(\S+)\s+"([^"]+)"', attr_str):
        key = match.group(1)
        value = match.group(2)
        attrs[key] = value
    return attrs


def normalize_build(build: str) -> str:
    build = build.strip().lower()
    if build in {"grch37", "37", "hg19"}:
        return "hg19"
    if build in {"grch38", "38", "hg38"}:
        return "hg38"
    if build in {"t2t", "hs1", "chm13"}:
        return "t2t"
    fail(f"Unsupported build: {build}")
    return build


# ---------------------------------------------------------------------
# GTF -> BED builders
# ---------------------------------------------------------------------

def build_genes_bed(gtf_path: Path, out_bed: Path) -> int:
    """
    Build a BED4 genes file from all gene records in the GTF.

    BED4 columns:
      chrom  start  end  name

    name format:
      gene_name|gene_id|gene_type
    """
    count = 0
    with open_text_auto(gtf_path) as inp, out_bed.open("w") as out:
        for line in inp:
            if not line.strip() or line.startswith("#"):
                continue

            parts = line.rstrip("\n").split("\t")
            if len(parts) != 9:
                continue

            chrom, source, feature, start, end, score, strand, frame, attrs = parts
            if feature != "gene":
                continue

            attr = parse_gtf_attributes(attrs)
            gene_id = attr.get("gene_id", "NA")
            gene_name = attr.get("gene_name", gene_id)
            gene_type = attr.get("gene_type", attr.get("gene_biotype", "NA"))

            # GTF is 1-based inclusive; BED is 0-based half-open
            bed_start = max(0, int(start) - 1)
            bed_end = int(end)

            name = f"{gene_name}|{gene_id}|{gene_type}"
            out.write(f"{chrom}\t{bed_start}\t{bed_end}\t{name}\n")
            count += 1

    return count


def build_exons_bed(gtf_path: Path, out_bed: Path) -> int:
    """
    Build a BED4 exons file from all exon records in the GTF.

    name format:
      gene_name|gene_id|transcript_id|exon_number
    """
    count = 0
    with open_text_auto(gtf_path) as inp, out_bed.open("w") as out:
        for line in inp:
            if not line.strip() or line.startswith("#"):
                continue

            parts = line.rstrip("\n").split("\t")
            if len(parts) != 9:
                continue

            chrom, source, feature, start, end, score, strand, frame, attrs = parts
            if feature != "exon":
                continue

            attr = parse_gtf_attributes(attrs)
            gene_id = attr.get("gene_id", "NA")
            gene_name = attr.get("gene_name", gene_id)
            transcript_id = attr.get("transcript_id", "NA")
            exon_number = attr.get("exon_number", "NA")

            bed_start = max(0, int(start) - 1)
            bed_end = int(end)

            name = f"{gene_name}|{gene_id}|{transcript_id}|{exon_number}"
            out.write(f"{chrom}\t{bed_start}\t{bed_end}\t{name}\n")
            count += 1

    return count


def build_promoters_bed(
    gtf_path: Path,
    out_bed: Path,
    upstream_bp: int = 2000,
    downstream_bp: int = 500,
) -> int:
    """
    Build a BED4 promoter file from all transcript records in the GTF.

    Promoter definition
    -------------------
    For '+' strand:
      [TSS - upstream_bp, TSS + downstream_bp)

    For '-' strand:
      [TSS - downstream_bp, TSS + upstream_bp)

    name format:
      gene_name|gene_id|transcript_id|strand
    """
    count = 0
    with open_text_auto(gtf_path) as inp, out_bed.open("w") as out:
        for line in inp:
            if not line.strip() or line.startswith("#"):
                continue

            parts = line.rstrip("\n").split("\t")
            if len(parts) != 9:
                continue

            chrom, source, feature, start, end, score, strand, frame, attrs = parts
            if feature != "transcript":
                continue

            attr = parse_gtf_attributes(attrs)
            gene_id = attr.get("gene_id", "NA")
            gene_name = attr.get("gene_name", gene_id)
            transcript_id = attr.get("transcript_id", "NA")

            start_i = int(start)
            end_i = int(end)

            if strand == "+":
                tss = start_i
                bed_start = max(0, tss - 1 - upstream_bp)
                bed_end = tss - 1 + downstream_bp
            else:
                tss = end_i
                bed_start = max(0, tss - 1 - downstream_bp)
                bed_end = tss - 1 + upstream_bp

            name = f"{gene_name}|{gene_id}|{transcript_id}|{strand}"
            out.write(f"{chrom}\t{bed_start}\t{bed_end}\t{name}\n")
            count += 1

    return count


# ---------------------------------------------------------------------
# Manifest writer
# ---------------------------------------------------------------------

def write_manifest(manifest_path: Path, rows: list[dict[str, str]]) -> None:
    header = [
        "build",
        "resource_type",
        "source_kind",
        "source",
        "installed_path",
        "notes",
    ]
    with manifest_path.open("w", newline="") as out:
        writer = csv.DictWriter(out, fieldnames=header, delimiter="\t")
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


# ---------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Set up Breakdance reference directories for hg19, hg38, or T2T."
    )

    parser.add_argument(
        "--build",
        required=True,
        help="Reference build: hg19, hg38, or t2t",
    )
    parser.add_argument(
        "--reference-root",
        required=True,
        help="Top-level reference root directory",
    )

    # Optional local files
    parser.add_argument("--fasta", default=None, help="Local genome FASTA(.gz) path")
    parser.add_argument("--gtf", default=None, help="Local annotation GTF(.gz) path")
    parser.add_argument("--enhancers-bed", default=None, help="Local enhancer BED4 file")

    # Optional download URLs
    parser.add_argument("--fasta-url", default=None, help="URL for genome FASTA(.gz)")
    parser.add_argument("--gtf-url", default=None, help="URL for annotation GTF(.gz)")
    parser.add_argument("--enhancers-bed-url", default=None, help="URL for enhancer BED4")

    # Behavior
    parser.add_argument(
        "--symlink-local-files",
        action="store_true",
        help="Symlink local files instead of copying them",
    )
    parser.add_argument(
        "--promoter-upstream-bp",
        type=int,
        default=2000,
        help="Promoter upstream window size in bp",
    )
    parser.add_argument(
        "--promoter-downstream-bp",
        type=int,
        default=500,
        help="Promoter downstream window size in bp",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Allow overwriting existing generated files",
    )

    return parser.parse_args()


def main() -> None:
    args = parse_args()

    build = normalize_build(args.build)
    defaults = DEFAULTS[build]

    reference_root = Path(args.reference_root)
    build_root = reference_root / build

    genome_dir = build_root / "genome"
    gtf_dir = build_root / "annotation" / "gtf"
    bed_dir = build_root / "annotation" / "bed"
    source_dir = build_root / "source_files"
    manifest_dir = build_root / "manifests"

    for d in (genome_dir, gtf_dir, bed_dir, source_dir, manifest_dir):
        ensure_dir(d)

    manifest_rows: list[dict[str, str]] = []

    # Resolve source FASTA/GTF
    fasta_local = Path(args.fasta) if args.fasta else None
    gtf_local = Path(args.gtf) if args.gtf else None

    fasta_url = args.fasta_url if args.fasta_url else defaults["fasta_url"]
    gtf_url = args.gtf_url if args.gtf_url else defaults["gtf_url"]

    if fasta_local is None and fasta_url is None:
        fail(f"No FASTA source available for build {build}. Provide --fasta or --fasta-url.")

    if gtf_local is None and gtf_url is None:
        fail(f"No GTF source available for build {build}. Provide --gtf or --gtf-url.")

    # Install FASTA
    fasta_dest_name = "genome.fa.gz" if ((fasta_local and str(fasta_local).endswith(".gz")) or (fasta_url and fasta_url.endswith(".gz"))) else "genome.fa"
    fasta_dest = genome_dir / fasta_dest_name

    if fasta_dest.exists() and not args.force:
        fail(f"FASTA already exists. Use --force to overwrite: {fasta_dest}")

    if fasta_local:
        copy_or_symlink(fasta_local, fasta_dest, symlink=args.symlink_local_files)
        manifest_rows.append({
            "build": build,
            "resource_type": "genome_fasta",
            "source_kind": "local",
            "source": str(fasta_local),
            "installed_path": str(fasta_dest),
            "notes": defaults["build_label"],
        })
    else:
        download_file(fasta_url, fasta_dest)
        manifest_rows.append({
            "build": build,
            "resource_type": "genome_fasta",
            "source_kind": "url",
            "source": fasta_url,
            "installed_path": str(fasta_dest),
            "notes": defaults["build_label"],
        })

    # Install GTF
    gtf_dest_name = "genes.gtf.gz" if ((gtf_local and str(gtf_local).endswith(".gz")) or (gtf_url and gtf_url.endswith(".gz"))) else "genes.gtf"
    gtf_dest = gtf_dir / gtf_dest_name

    if gtf_dest.exists() and not args.force:
        fail(f"GTF already exists. Use --force to overwrite: {gtf_dest}")

    if gtf_local:
        copy_or_symlink(gtf_local, gtf_dest, symlink=args.symlink_local_files)
        manifest_rows.append({
            "build": build,
            "resource_type": "annotation_gtf",
            "source_kind": "local",
            "source": str(gtf_local),
            "installed_path": str(gtf_dest),
            "notes": defaults["build_label"],
        })
    else:
        download_file(gtf_url, gtf_dest)
        manifest_rows.append({
            "build": build,
            "resource_type": "annotation_gtf",
            "source_kind": "url",
            "source": gtf_url,
            "installed_path": str(gtf_dest),
            "notes": defaults["build_label"],
        })

    # Generate BED files from GTF
    genes_bed = bed_dir / "genes.bed"
    exons_bed = bed_dir / "exons.bed"
    promoters_bed = bed_dir / "promoters.bed"
    enhancers_bed = bed_dir / "enhancers.bed"

    for bed_path in (genes_bed, exons_bed, promoters_bed):
        if bed_path.exists() and not args.force:
            fail(f"Output BED already exists. Use --force to overwrite: {bed_path}")

    log("Building genes BED...")
    gene_count = build_genes_bed(gtf_dest, genes_bed)
    manifest_rows.append({
        "build": build,
        "resource_type": "genes_bed",
        "source_kind": "generated_from_gtf",
        "source": str(gtf_dest),
        "installed_path": str(genes_bed),
        "notes": f"{gene_count} gene records",
    })

    log("Building exons BED...")
    exon_count = build_exons_bed(gtf_dest, exons_bed)
    manifest_rows.append({
        "build": build,
        "resource_type": "exons_bed",
        "source_kind": "generated_from_gtf",
        "source": str(gtf_dest),
        "installed_path": str(exons_bed),
        "notes": f"{exon_count} exon records",
    })

    log("Building promoters BED...")
    promoter_count = build_promoters_bed(
        gtf_dest,
        promoters_bed,
        upstream_bp=args.promoter_upstream_bp,
        downstream_bp=args.promoter_downstream_bp,
    )
    manifest_rows.append({
        "build": build,
        "resource_type": "promoters_bed",
        "source_kind": "generated_from_gtf",
        "source": str(gtf_dest),
        "installed_path": str(promoters_bed),
        "notes": f"{promoter_count} promoter intervals; upstream={args.promoter_upstream_bp}, downstream={args.promoter_downstream_bp}",
    })

    # Optional enhancer BED
    enhancer_local = Path(args.enhancers_bed) if args.enhancers_bed else None
    enhancer_url = args.enhancers_bed_url

    if enhancer_local or enhancer_url:
        if enhancers_bed.exists() and not args.force:
            fail(f"Enhancer BED already exists. Use --force to overwrite: {enhancers_bed}")

        if enhancer_local:
            copy_or_symlink(enhancer_local, enhancers_bed, symlink=args.symlink_local_files)
            manifest_rows.append({
                "build": build,
                "resource_type": "enhancers_bed",
                "source_kind": "local",
                "source": str(enhancer_local),
                "installed_path": str(enhancers_bed),
                "notes": "User-supplied enhancer BED4",
            })
        else:
            download_file(enhancer_url, enhancers_bed)
            manifest_rows.append({
                "build": build,
                "resource_type": "enhancers_bed",
                "source_kind": "url",
                "source": enhancer_url,
                "installed_path": str(enhancers_bed),
                "notes": "User-supplied enhancer BED4 URL",
            })
    else:
        log("No enhancer BED supplied. Leaving enhancers.bed absent.")
        manifest_rows.append({
            "build": build,
            "resource_type": "enhancers_bed",
            "source_kind": "not_installed",
            "source": "",
            "installed_path": str(enhancers_bed),
            "notes": "No enhancer BED provided; optional resource",
        })

    # Write manifest
    manifest_path = manifest_dir / "reference_manifest.tsv"
    write_manifest(manifest_path, manifest_rows)

    log("============================================================")
    log("Reference setup complete")
    log("============================================================")
    log(f"Build                 : {build}")
    log(f"Reference root        : {build_root}")
    log(f"Genome FASTA          : {fasta_dest}")
    log(f"GTF                   : {gtf_dest}")
    log(f"Genes BED             : {genes_bed}")
    log(f"Exons BED             : {exons_bed}")
    log(f"Promoters BED         : {promoters_bed}")
    log(f"Enhancers BED         : {enhancers_bed if enhancers_bed.exists() else '[not installed]'}")
    log(f"Manifest              : {manifest_path}")
    log("============================================================")


if __name__ == "__main__":
    main()
